name: phiqwenstem

networks:
  mynet:
    driver: bridge

services:

  database:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    networks:
      - mynet
    volumes:
      - "./qdrant_storage:/qdrant/storage"

  ui:
    build:
      context: ./chatbot-ui/
      dockerfile: Dockerfile 
    ports:
      - "8501:8501"
    networks:
      - mynet
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    networks:
      - mynet
    secrets:
      - huggingface_api_token

secrets:
  huggingface_api_token: 
    environment: hf_token